### ISSUE TITLE
2.2.0-2: problem retrieving `max_queuable` from queue params

### ISSUE THREAD

**Issue by jouvin** [GRIF/lcg-info-dynamic-maui#6]
@edithknoops reported the following error with 2.2.0-2:

```
/var/spool/maui/gip-info-dynamic-ce-plugin.sh
Traceback (most recent call last):
File "/usr/libexec/lcg-info-dynamic-maui", line 372, in 
queue_attrs[queue]['MaxWaitingJobs'] = queue_attrs[queue]['max_queuable'][0] - queue_attrs[queue]['MaxRunningJobs']
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

`/etc/lrms/lcg-info-dynamic-maui.defaults` content is:

```
MaxPhysicalMemory=2000
MaxProcessorsPerJob=1
MaxVirtualMemory=20000
```

**Comment by jouvin** [comment]
@edithknoops could you download the last revision of `lcg-info-dynamic-maui` using:

```
git clone https://github.com/GRIF/lcg-info-dynamic-maui.git
```

Then edit `/var/spool/maui/gip-info-dynamic-ce-plugin.sh` and add `$*` at the end of the line invoking `lcg-info-dynamic-maui`.

This new version just adds more debug information. Could you then send me (privately) the log file produced by:

```
 /tmp/gip-info-dynamic-ce-plugin.sh --debug >&/tmp/log
```

**Comment by jouvin** [comment]
@edithknoops please could you test version 2.2.0-3 (can be retrieved from usual http://quattorsrv.lal.in2p3.fr/packages/os/sl6/addons).

**Comment by edithknoops** [comment]
It is ok with version 2.2.0-3
